os: osx
language: cpp
addons:
  homebrew:
    packages:
    - scons
    - yaml-cpp
    - p7zip
    update: true
git:
  submodules: false
script:
- git submodule update --init --recursive godot-cpp
- cd godot-cpp
- scons platform=osx headers=godot_headers generate_bindings=yes target=release
- cd ..
- scons platform=osx target=release
before_deploy:
- cd demo/bin
- 7z a -t7z -mx9 "${TRAVIS_BUILD_DIR}/godot-yaml-${TRAVIS_BUILD_NUMBER}-osx-release.7z"
deploy:
  provider: releases
  api_key:
    secure: HcT0mlFpsP+NjUtsMz8JKBOpDfYyGYTYNFvSSJ5M9Hd1AmE8m07/gu6p8oijgNItgKqWW/jJBf2tq0XAxpFDJU0KD4Xzta2VJcRphd4mRXyCc9b/G6gtswhHwx5jLM/ID/oGeA6nMjItT39mPe6ujTwHNdSvI4ObG4KSRcHhEmGNxoMRh/51S8z3i2qWb82XxpBS2exBCPBakFTh8jF2DqIpJCPn7G13jbfQZQhxQr6FBGlKFYo/iH1fCGWzaOvNA2NJlf0VNzXDOIGbGP/3d/kQ4KSgdImADaNN7+hdWS59vACDpE2cX4PW542Cl5i5Fs9CL61G6sJTcWAqcZsndq/y7NUY2sIIUk18YkgyIP9tYVWXpVtPbnBY2TT7jGn0lfTIR+M5T1WxXbWxLweht/9PJEUOuTou0jPV8RerY0oQILnF6o0cSV8H6bTpoSs5baXZD/h2QTG/VDGgKPC0KXoZh4T1zv5f+sCtahgTglhRUni1xDlSEi6Pm18L1Y/LcQRyZZTS3TeFFR3Hxe87aeDCVcNw1Kk3voLIduvoBan2Ugq9tH9xVtyf1FXtAyEtHLs1FFWKlGFDWaEmaYxwzFFG8YseuL/fkOzFCaEgSdBpi7API11bI0K/k4IOj7f4ruVFcnR7+HjzsziTCzXBqcogLqaAClYqlL1ZdEtyGIU=
  file: "${TRAVIS_BUILD_DIR}/godot-yaml-${TRAVIS_BUILD_NUMBER}-osx-release.7z"
  skip_cleanup : true
  on:
    tags: true
